MALFORMED_NUMBER = '^\-?\s*[0-9]+(\..*[^0-9]+.*$|.*[^0-9\.]+.*|\.$)'
MALFORMED_IDENTIFIER = '([a-z]|[A-Z]).*[^(\w|\d|\_)].*'
MALFORMED_OPERATOR = '(\+\+(\+\+*))|(\-\-(\-\-*))'
MALFORMED_COMMENT = ''
MALFORMED_STRING = ''
INVALID_SYMBOL = ''