from .lexical import ARITHMETIC_OPERATORS, RELATIONAL_OPERATORS, LOGICAL_OPERATORS, RESERVED_WORDS, BLOCK_COMMENT, LINE_COMMENT, IDENTIFIERS, DELIMITERS, NUMBER, STRING, NEWLINE, SKIP
from .types import ART_TK, CAD_TK, DEL_TK, IDE_TK, LOG_TK, NRO_TK, PRE_TK, REL_TK, NWL_TK, SKP_TK, BCM_TK, LCM_TK, IDE_TK
from .errors import MALFORMED_IDENTIFIER

# Token map composed by the (tokenType, value) pair
TOKEN_MAP = [
  (ART_TK, ARITHMETIC_OPERATORS),
  (REL_TK, RELATIONAL_OPERATORS),
  (LOG_TK, LOGICAL_OPERATORS),
  (BCM_TK, BLOCK_COMMENT),
  (LCM_TK, LINE_COMMENT),
  (IDE_TK, IDENTIFIERS),
  (DEL_TK, DELIMITERS),
  (NWL_TK, NEWLINE),
  (CAD_TK, STRING),
  (NRO_TK, NUMBER),
  (SKP_TK, SKIP)
]

ERROR_TOKEN_MAP = [
  (IDE_TK, MALFORMED_IDENTIFIER)
]