from .lexical import ARITHMETIC_OPERATORS, RELATIONAL_OPERATORS, LOGICAL_OPERATORS, RESERVED_WORDS, BLOCK_COMMENT, LINE_COMMENT, IDENTIFIERS, DELIMITERS, NUMBER, STRING, NEWLINE, SKIP
from .types import ART_TK, CAD_TK, DEL_TK, IDE_TK, LOG_TK, NRO_TK, PRE_TK, REL_TK, NWL_TK, SKP_TK, BCM_TK, LCM_TK, IDE_TK, OPMF_TK, COMF_TK, SIB_TK, CMF_TK, NMF_TK
from .errors import MALFORMED_OPERATOR, INVALID_SYMBOL, MALFORMED_COMMENT, MALFORMED_NUMBER, MALFORMED_STRING

# Token map composed by the (tokenType, value) pair
TOKEN_MAP = [
  (LCM_TK, LINE_COMMENT),
  (BCM_TK, BLOCK_COMMENT),
  (ART_TK, ARITHMETIC_OPERATORS),
  (REL_TK, RELATIONAL_OPERATORS),
  (LOG_TK, LOGICAL_OPERATORS),
  (IDE_TK, IDENTIFIERS),
  (DEL_TK, DELIMITERS),
  (NWL_TK, NEWLINE),
  (CAD_TK, STRING),
  (NRO_TK, NUMBER),
  (SKP_TK, SKIP)
]

ERROR_TOKEN_MAP = [
  (COMF_TK, MALFORMED_COMMENT),
  (OPMF_TK, MALFORMED_OPERATOR),
  (NMF_TK, MALFORMED_NUMBER),
  (CAD_TK, MALFORMED_STRING),
  #(SIB_TK, INVALID_SYMBOL),
  (NWL_TK, NEWLINE),
  (SKP_TK, SKIP)
]