# Tokens
ART_TK = 'ART'
REL_TK = 'REL'
LOG_TK = 'LOG'
PRE_TK = 'PRE'
IDE_TK = 'IDE'
NRO_TK = 'NRO'
DEL_TK = 'DEL'
CAD_TK = 'CAD'

# Errors
SIB_TK = 'SIB'
CMF_TK = 'CMF'
NMF_TK = 'NMF'
CMF_TK = 'COMF'
OMF_TK = 'OPMF'

# Not printed
BCM_TK = 'BLOCK_COMMENT'
LCM_TK = 'LINE_COMMENT'
NWL_TK = 'NEWLINE'
SKP_TK = 'SKIP'